### ISSUE TITLE
question about Two-Tier Hash Table used in Snoopy

### ISSUE THREAD

**Issue by dorafan** [myl7/oht#3]
Hi, I have a stupid question. In Snoopy they say they use Two-Tier Hash Table in the subOram instead of the Oblix way. But I couldn't find the code of the Two-Tier Hash Table (oht)....... until I found this repo.

However, it looks like they indeed have buckets and blocks in subOram. 

Would you mind providing any info about this question?

**Comment by myl7** [comment]
I spent lots of time on ucbrise/snoopy but still have not got a complete view of their implementation, which is part of the reason why I created this repo to reimplement.

https://github.com/ucbrise/snoopy/blob/da4c98e3876c10cf52aa51ece3b62c5e8b8e335a/suboram/enc/suboram.h#L37 may have something about the hash table rebuilding, but I have never made it run well.

**Comment by dorafan** [comment]
Thanks a lot for your response! Your oht really helps me (I still can't identify Snoopy's oht lol, but that's fine)
